apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xfvfc8gi9-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xfvfc8gi9-go 
  name: xfvfc8gi9-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xfvfc8gi9-go 
