apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xfvfc8gi9-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:6fcda8457fb157e8d7841516c2a67356cb68a75a@sha256:34de5b96c70e08fe2c17e15483a10db7dcdb5e7fe59dfd449e180e2ae743f679
          name: container-image
