apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xfvfc8gi9-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:33ac4e3af109856f70398ebd2be4592fccea01d3@sha256:ad5e9e12175e83cd53a58b5acab5d98550f9a916b8d98efe15adcc861bea1a05
          name: container-image
